import Head from "next/head";
import FullPageWithSidebar from "../layouts/FullPageWithSidebar";
import Menu from "../components/Menu";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Dynamic Routes POC</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <FullPageWithSidebar sideBarContent={<Menu />}>
                <h1>Dynamic Menu PoC</h1>
            </FullPageWithSidebar>
        </div>
    );
}
