import Head from "next/head";

import MerlinPage from "./[...slug]";

export default function Home({ menuData }) {
    return (
        <div>
            <Head>
                <title>Dynamic Routes POC</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MerlinPage menuData={menuData} />
        </div>
    );
}
